---
include:
  - board: nice_nano_v2
    shield: elexx_split64_v1_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: elexx_split64_v1_right
  - board: nice_nano_v2
    shield: settings_reset
